services:
  frontend:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - IS_CONTAINERIZED=true
    ports:
      - 5173:5173
    stdin_open: true
    volumes:
      - /usr/src/app/node_modules
    networks:
      - react-express
    develop:
      watch:
        - action: sync
          path: ./
          target: /usr/src/app
          ignore:
            - node_modules
            - server
            - scripts

  backend:
    restart: always
    build:
      context: ./
      dockerfile: server/Dockerfile
      target: development
    depends_on:
      - elasticsearch
      - redis
    env_file:
      - .env
    environment:
      - IS_CONTAINERIZED=true
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - react-express
      - express-elastic
      - express-redis
    expose:
      - 3000
    # for some reason, watch isn't actually reflecting changes in the server
    # develop:
    #   watch:
    #     - action: sync+restart
    #       path: ./server
    #       target: /usr/src/app/server
    #     - action: sync+restart
    #       path: ./shared
    #       target: /usr/src/app/shared
    #     - action: sync+restart
    #       path: ./scripts
    #       target: /usr/src/app/scripts

  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ES_LOG_STYLE=console
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - express-elastic

  redis:
    restart: always
    image: redis/redis-stack:latest
    environment:
      - REDIS_ARGS=--save 300 20 --appendonly yes # enable persistence by saving every 5 minutes if at least 20 changes have been made
    ports:
      - "6379:6379" # Redis server port
      - "8001:8001" # RedisInsight web UI port
    volumes:
      - redis_data:/usr/share/redis/data
    networks:
      - express-redis

networks:
  react-express:
  express-elastic:
  express-redis:

volumes:
  mongo_data:
  elasticsearch_data:
  redis_data:
